name: nimon
description: NIMON demo
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  uuid: ^4.4.2
  collection: ^1.18.0
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  flutter_riverpod: ^2.4.9
  animated_accordion: ^1.1.1
  image_picker: ^1.0.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
